### PR TITLE
Dynamically generate plists

### PR DESCRIPTION
**Pull request by gabriel**
Code dynamically generates plists instead of passing env vars via launchctl.

### CODE REVIEW

**Comment by gabriel** [comment]
@cjb

**Comment by cjb** [comment]
@gabriel huh, how does $RELEASE_TO_PROMOTE get through now?

**Comment by gabriel** [comment]
`setDarwinEnv("RELEASE_TO_PROMOTE")`

This passing vars through env thing is a huge hack. I'll make a PR to generate plists dynamically which is what the right thing to do is.

**Comment by cjb** [comment]
Ah, okay -- please could I get you to update my branch too?

**Comment by gabriel** [comment]
k, updated your branch...

Yeah this env stuff is crazy, if we dynamically build the job (plist), as I've done in this latest PR change, then it's way better (and also fixes hardcoding dirs and go paths etc)

I'm just trying it for release promote but we can update the other commands to generate plist dynamically too if we like it

**Pull request merged**
